from ..FzfPrompt.options.actions import BaseAction
from ..FzfPrompt.options.events import Hotkey, Situation


# Used to generate EventAdder using AI
FZF_EVENTS: dict[Situation, str] = {
    "start": "Triggered only once when fzf finder starts. Since fzf consumes the input stream asynchronously, the input list is not available unless you use --sync",
    "load": "Triggered when the input stream is complete and the initial processing of the list is complete",
    "resize": "Triggered when the terminal size is changed",
    "result": "Triggered when the filtering for the current query is complete and the result list is ready",
    "change": "Triggered whenever the query string is changed",
    "focus": "Triggered when the focus changes due to a vertical cursor movement or a search result update",
    "one": "Triggered when there's only one match",
    "zero": "Triggered when there's no match",
    "backward-eof": "Triggered when the query string is already empty and you try to delete it backward",
}

DEFAULT_FZF_BINDINGS: dict[Hotkey, BaseAction | None] = {
    "alt-0": None,
    "alt-1": None,
    "alt-2": None,
    "alt-3": None,
    "alt-4": None,
    "alt-5": None,
    "alt-6": None,
    "alt-7": None,
    "alt-8": None,
    "alt-9": None,
    "alt-a": None,
    "alt-b": "backward-word",
    "alt-bs": "backward-kill-word",
    "alt-c": None,
    "alt-d": "kill-word",
    "alt-down": None,
    "alt-e": None,
    "alt-f": "forward-word",
    "alt-g": None,
    "alt-h": None,
    "alt-i": None,
    "alt-j": None,
    "alt-k": None,
    "alt-l": None,
    "alt-m": None,
    "alt-n": None,
    "alt-o": None,
    "alt-p": None,
    "alt-q": None,
    "alt-r": None,
    "alt-s": None,
    "alt-t": None,
    "alt-u": None,
    "alt-up": None,
    "alt-v": None,
    "alt-w": None,
    "alt-x": None,
    "alt-y": None,
    "alt-z": None,
    "bspace": "backward-delete-char",
    "ctrl-6": None,
    "ctrl-a": "beginning-of-line",
    "ctrl-alt-a": None,
    "ctrl-alt-b": None,
    "ctrl-alt-c": None,
    "ctrl-alt-d": None,
    "ctrl-alt-e": None,
    "ctrl-alt-f": None,
    "ctrl-alt-g": None,
    "ctrl-alt-h": None,
    "ctrl-alt-i": None,
    "ctrl-alt-j": None,
    "ctrl-alt-k": None,
    "ctrl-alt-l": None,
    "ctrl-alt-m": None,
    "ctrl-alt-n": None,
    "ctrl-alt-o": None,
    "ctrl-alt-p": None,
    "ctrl-alt-q": None,
    "ctrl-alt-r": None,
    "ctrl-alt-s": None,
    "ctrl-alt-t": None,
    "ctrl-alt-u": None,
    "ctrl-alt-v": None,
    "ctrl-alt-w": None,
    "ctrl-alt-x": None,
    "ctrl-alt-y": None,
    "ctrl-alt-z": None,
    "ctrl-b": "backward-char",
    "ctrl-c": "abort",
    "ctrl-d": "delete-char/eof",
    "ctrl-e": "end-of-line",
    "ctrl-f": "forward-char",
    "ctrl-g": "abort",
    "ctrl-h": "backward-delete-char",
    "ctrl-i": "toggle+down",
    "ctrl-j": "down",
    "ctrl-k": "up",
    "ctrl-l": "clear-screen",
    "ctrl-n": "down",
    "ctrl-o": None,
    "ctrl-p": "up",
    "ctrl-q": "abort",
    "ctrl-r": None,
    "ctrl-s": None,
    "ctrl-t": None,
    "ctrl-u": "unix-line-discard",
    "ctrl-v": None,
    "ctrl-w": "unix-word-rubout",
    "ctrl-x": None,
    "ctrl-y": "yank",
    "ctrl-z": None,
    "del": "delete-char",
    "double-click": "accept",
    "down": "down",
    "end": "end-of-line",
    "enter": "accept",
    "esc": "abort",
    "f1": None,
    "f2": None,
    "f3": None,
    "f4": None,
    "f5": None,
    "f6": None,
    "f7": None,
    "f8": None,
    "f9": None,
    "f10": None,
    "f11": None,
    "f12": None,
    "home": "beginning-of-line",
    "left": "backward-char",
    "pgdn": "page-down",
    "pgup": "page-up",
    "right": "forward-char",
    "right-click": "toggle",
    "shift-down": "preview-down",
    "shift-left": "backward-word",
    "shift-right": "forward-word",
    "shift-tab": "toggle+up",
    "shift-up": "preview-up",
    "tab": "toggle+down",
    "up": "up",
}
