from typing import Literal

# raw fzf actions that aren't parametrized
BaseAction = Literal[
    "abort",
    "accept",
    "accept-non-empty",
    "backward-char",
    "backward-delete-char",
    "backward-delete-char/eof",
    "backward-kill-word",
    "backward-word",
    "beginning-of-line",
    "cancel",
    "clear-screen",
    "clear-selection",
    "close",
    "clear-query",
    "delete-char",
    "delete-char/eof",
    "deselect",
    "deselect-all",
    "disable-search",
    "down",
    "enable-search",
    "end-of-line",
    "first",
    "forward-char",
    "forward-word",
    "ignore",
    "jump",
    "jump-accept",
    "kill-line",
    "kill-word",
    "last",
    "next-history",
    "page-down",
    "page-up",
    "half-page-down",
    "half-page-up",
    "preview-down",
    "preview-up",
    "preview-page-down",
    "preview-page-up",
    "preview-half-page-down",
    "preview-half-page-up",
    "preview-bottom",
    "preview-top",
    "previous-history",
    "print-query",
    "refresh-preview",
    "replace-query",
    "select",
    "select-all",
    "toggle",
    "toggle-all",
    "toggle+down",
    "toggle-in",
    "toggle-out",
    "toggle-preview",
    "toggle-preview-wrap",
    "toggle-search",
    "toggle-sort",
    "toggle+up",
    "unix-line-discard",
    "unix-word-rubout",
    "up",
    "yank",
]

# fzf actions that require an extra value
ParametrizedActionType = Literal[
    "change-preview",
    "change-preview-window",
    "change-prompt",
    "execute",
    "execute-silent",
    "preview",
    "put",
    "rebind",
    "reload",
    "unbind",
]

# those parametrized actions whose value is a shell command
ShellCommandActionType = Literal[
    "execute",
    "execute-silent",
    "change-preview",
    "change-prompt",
    "reload",
]
